---
name: Build stm32

on: [workflow_dispatch, push, pull_request_target, pull_request]

defaults:
  run:
    working-directory: ./stm32

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: stm32/.pio/build

  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run static code analysis
        run: pio check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-cpplint

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install cpplint
        run: pip install --upgrade cpplint==1.6.1

      - name: Run linter
        run: cpplint --recursive lib Src/examples test

  test:
    runs-on: ubuntu-latest
    concurrency:
      group: remote-test
    needs: build
    env:
      protobuf_library: SoilPowerSensorProtocalBuffer-${{ github.sha }}.tar.gz
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Pack protobuf package
        run: pio pkg pack -o ${{ env.protobuf_library }} proto/c

      - name: Upload package artifact
        id: upload-protobuf-package
        uses: actions/upload-artifact@v4
        with:
          name: protobuf-library
          path: ${{ env.protobuf_library }}
          retention-days: 1

      - name: Replace protobuf package reference
        env:
          lib_url: ${{ steps.upload-protobuf-package.outputs.artifact_url }}
        run: sed -i 's|\(Soil Power Sensor Protocal Buffer\).*|\1=${{ env.lib_url }}|' stm32/platformio.ini

      - name: Run unit tests
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: pio remote test -e tests -r
